name: Code Climate

on:
  push:
    branches:
      - master

env:
  FORCE_COLOR: 1

jobs:
  rubocop:
    name: Codeclimate:Rubocop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Ruby 2.6.5
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.6.5
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v4
      with:
        PATTERNS: |
          +(app|__tests__)/**/*.rb
          !src/exclude.ts
        FILES: |
          yarn.lock
          .eslintrc
      - name: Install Rubocop Gems
        if: env.GIT_DIFF
        run: |
          gem install rubocop -v '0.92.0'
          gem install rubocop-performance -v '1.8.1'
          gem install rubocop-rails -v '2.8.1'
          gem install rubocop-rspec -v '1.43.2'
      - name: Check code style
        # Check only if there are differences in the source code
        run: rubocop
        if: env.GIT_DIFF

 